package com.common.model.auto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PersonQuestionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person_question
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person_question
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person_question
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     *
     */
    public PersonQuestionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *
     * @param orderByClause
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *
     * @param distinct
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     *
     * @param criteria
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     *
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 类注释
     * GeneratedCriteria
     * 数据库表：person_question
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOpenIdIsNull() {
            addCriterion("open_id is null");
            return (Criteria) this;
        }

        public Criteria andOpenIdIsNotNull() {
            addCriterion("open_id is not null");
            return (Criteria) this;
        }

        public Criteria andOpenIdEqualTo(String value) {
            addCriterion("open_id =", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotEqualTo(String value) {
            addCriterion("open_id <>", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdGreaterThan(String value) {
            addCriterion("open_id >", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdGreaterThanOrEqualTo(String value) {
            addCriterion("open_id >=", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLessThan(String value) {
            addCriterion("open_id <", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLessThanOrEqualTo(String value) {
            addCriterion("open_id <=", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLike(String value) {
            addCriterion("open_id like", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotLike(String value) {
            addCriterion("open_id not like", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdIn(List<String> values) {
            addCriterion("open_id in", values, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotIn(List<String> values) {
            addCriterion("open_id not in", values, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdBetween(String value1, String value2) {
            addCriterion("open_id between", value1, value2, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotBetween(String value1, String value2) {
            addCriterion("open_id not between", value1, value2, "openId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(Integer value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(Integer value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(Integer value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(Integer value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(Integer value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<Integer> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<Integer> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(Integer value1, Integer value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(Integer value1, Integer value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Integer value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Integer value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Integer value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Integer value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Integer value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Integer> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Integer> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Integer value1, Integer value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Integer value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Integer value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Integer value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Integer value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Integer value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Integer> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Integer> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Integer value1, Integer value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHSmkIsNull() {
            addCriterion("h_smk is null");
            return (Criteria) this;
        }

        public Criteria andHSmkIsNotNull() {
            addCriterion("h_smk is not null");
            return (Criteria) this;
        }

        public Criteria andHSmkEqualTo(Integer value) {
            addCriterion("h_smk =", value, "hSmk");
            return (Criteria) this;
        }

        public Criteria andHSmkNotEqualTo(Integer value) {
            addCriterion("h_smk <>", value, "hSmk");
            return (Criteria) this;
        }

        public Criteria andHSmkGreaterThan(Integer value) {
            addCriterion("h_smk >", value, "hSmk");
            return (Criteria) this;
        }

        public Criteria andHSmkGreaterThanOrEqualTo(Integer value) {
            addCriterion("h_smk >=", value, "hSmk");
            return (Criteria) this;
        }

        public Criteria andHSmkLessThan(Integer value) {
            addCriterion("h_smk <", value, "hSmk");
            return (Criteria) this;
        }

        public Criteria andHSmkLessThanOrEqualTo(Integer value) {
            addCriterion("h_smk <=", value, "hSmk");
            return (Criteria) this;
        }

        public Criteria andHSmkIn(List<Integer> values) {
            addCriterion("h_smk in", values, "hSmk");
            return (Criteria) this;
        }

        public Criteria andHSmkNotIn(List<Integer> values) {
            addCriterion("h_smk not in", values, "hSmk");
            return (Criteria) this;
        }

        public Criteria andHSmkBetween(Integer value1, Integer value2) {
            addCriterion("h_smk between", value1, value2, "hSmk");
            return (Criteria) this;
        }

        public Criteria andHSmkNotBetween(Integer value1, Integer value2) {
            addCriterion("h_smk not between", value1, value2, "hSmk");
            return (Criteria) this;
        }

        public Criteria andHDrinkIsNull() {
            addCriterion("h_drink is null");
            return (Criteria) this;
        }

        public Criteria andHDrinkIsNotNull() {
            addCriterion("h_drink is not null");
            return (Criteria) this;
        }

        public Criteria andHDrinkEqualTo(Integer value) {
            addCriterion("h_drink =", value, "hDrink");
            return (Criteria) this;
        }

        public Criteria andHDrinkNotEqualTo(Integer value) {
            addCriterion("h_drink <>", value, "hDrink");
            return (Criteria) this;
        }

        public Criteria andHDrinkGreaterThan(Integer value) {
            addCriterion("h_drink >", value, "hDrink");
            return (Criteria) this;
        }

        public Criteria andHDrinkGreaterThanOrEqualTo(Integer value) {
            addCriterion("h_drink >=", value, "hDrink");
            return (Criteria) this;
        }

        public Criteria andHDrinkLessThan(Integer value) {
            addCriterion("h_drink <", value, "hDrink");
            return (Criteria) this;
        }

        public Criteria andHDrinkLessThanOrEqualTo(Integer value) {
            addCriterion("h_drink <=", value, "hDrink");
            return (Criteria) this;
        }

        public Criteria andHDrinkIn(List<Integer> values) {
            addCriterion("h_drink in", values, "hDrink");
            return (Criteria) this;
        }

        public Criteria andHDrinkNotIn(List<Integer> values) {
            addCriterion("h_drink not in", values, "hDrink");
            return (Criteria) this;
        }

        public Criteria andHDrinkBetween(Integer value1, Integer value2) {
            addCriterion("h_drink between", value1, value2, "hDrink");
            return (Criteria) this;
        }

        public Criteria andHDrinkNotBetween(Integer value1, Integer value2) {
            addCriterion("h_drink not between", value1, value2, "hDrink");
            return (Criteria) this;
        }

        public Criteria andDietIsNull() {
            addCriterion("diet is null");
            return (Criteria) this;
        }

        public Criteria andDietIsNotNull() {
            addCriterion("diet is not null");
            return (Criteria) this;
        }

        public Criteria andDietEqualTo(Integer value) {
            addCriterion("diet =", value, "diet");
            return (Criteria) this;
        }

        public Criteria andDietNotEqualTo(Integer value) {
            addCriterion("diet <>", value, "diet");
            return (Criteria) this;
        }

        public Criteria andDietGreaterThan(Integer value) {
            addCriterion("diet >", value, "diet");
            return (Criteria) this;
        }

        public Criteria andDietGreaterThanOrEqualTo(Integer value) {
            addCriterion("diet >=", value, "diet");
            return (Criteria) this;
        }

        public Criteria andDietLessThan(Integer value) {
            addCriterion("diet <", value, "diet");
            return (Criteria) this;
        }

        public Criteria andDietLessThanOrEqualTo(Integer value) {
            addCriterion("diet <=", value, "diet");
            return (Criteria) this;
        }

        public Criteria andDietIn(List<Integer> values) {
            addCriterion("diet in", values, "diet");
            return (Criteria) this;
        }

        public Criteria andDietNotIn(List<Integer> values) {
            addCriterion("diet not in", values, "diet");
            return (Criteria) this;
        }

        public Criteria andDietBetween(Integer value1, Integer value2) {
            addCriterion("diet between", value1, value2, "diet");
            return (Criteria) this;
        }

        public Criteria andDietNotBetween(Integer value1, Integer value2) {
            addCriterion("diet not between", value1, value2, "diet");
            return (Criteria) this;
        }

        public Criteria andActivityIsNull() {
            addCriterion("activity is null");
            return (Criteria) this;
        }

        public Criteria andActivityIsNotNull() {
            addCriterion("activity is not null");
            return (Criteria) this;
        }

        public Criteria andActivityEqualTo(Integer value) {
            addCriterion("activity =", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityNotEqualTo(Integer value) {
            addCriterion("activity <>", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityGreaterThan(Integer value) {
            addCriterion("activity >", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityGreaterThanOrEqualTo(Integer value) {
            addCriterion("activity >=", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityLessThan(Integer value) {
            addCriterion("activity <", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityLessThanOrEqualTo(Integer value) {
            addCriterion("activity <=", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityIn(List<Integer> values) {
            addCriterion("activity in", values, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityNotIn(List<Integer> values) {
            addCriterion("activity not in", values, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityBetween(Integer value1, Integer value2) {
            addCriterion("activity between", value1, value2, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityNotBetween(Integer value1, Integer value2) {
            addCriterion("activity not between", value1, value2, "activity");
            return (Criteria) this;
        }

        public Criteria andStressIsNull() {
            addCriterion("stress is null");
            return (Criteria) this;
        }

        public Criteria andStressIsNotNull() {
            addCriterion("stress is not null");
            return (Criteria) this;
        }

        public Criteria andStressEqualTo(Integer value) {
            addCriterion("stress =", value, "stress");
            return (Criteria) this;
        }

        public Criteria andStressNotEqualTo(Integer value) {
            addCriterion("stress <>", value, "stress");
            return (Criteria) this;
        }

        public Criteria andStressGreaterThan(Integer value) {
            addCriterion("stress >", value, "stress");
            return (Criteria) this;
        }

        public Criteria andStressGreaterThanOrEqualTo(Integer value) {
            addCriterion("stress >=", value, "stress");
            return (Criteria) this;
        }

        public Criteria andStressLessThan(Integer value) {
            addCriterion("stress <", value, "stress");
            return (Criteria) this;
        }

        public Criteria andStressLessThanOrEqualTo(Integer value) {
            addCriterion("stress <=", value, "stress");
            return (Criteria) this;
        }

        public Criteria andStressIn(List<Integer> values) {
            addCriterion("stress in", values, "stress");
            return (Criteria) this;
        }

        public Criteria andStressNotIn(List<Integer> values) {
            addCriterion("stress not in", values, "stress");
            return (Criteria) this;
        }

        public Criteria andStressBetween(Integer value1, Integer value2) {
            addCriterion("stress between", value1, value2, "stress");
            return (Criteria) this;
        }

        public Criteria andStressNotBetween(Integer value1, Integer value2) {
            addCriterion("stress not between", value1, value2, "stress");
            return (Criteria) this;
        }

        public Criteria andFamilysIsNull() {
            addCriterion("familys is null");
            return (Criteria) this;
        }

        public Criteria andFamilysIsNotNull() {
            addCriterion("familys is not null");
            return (Criteria) this;
        }

        public Criteria andFamilysEqualTo(Integer value) {
            addCriterion("familys =", value, "familys");
            return (Criteria) this;
        }

        public Criteria andFamilysNotEqualTo(Integer value) {
            addCriterion("familys <>", value, "familys");
            return (Criteria) this;
        }

        public Criteria andFamilysGreaterThan(Integer value) {
            addCriterion("familys >", value, "familys");
            return (Criteria) this;
        }

        public Criteria andFamilysGreaterThanOrEqualTo(Integer value) {
            addCriterion("familys >=", value, "familys");
            return (Criteria) this;
        }

        public Criteria andFamilysLessThan(Integer value) {
            addCriterion("familys <", value, "familys");
            return (Criteria) this;
        }

        public Criteria andFamilysLessThanOrEqualTo(Integer value) {
            addCriterion("familys <=", value, "familys");
            return (Criteria) this;
        }

        public Criteria andFamilysIn(List<Integer> values) {
            addCriterion("familys in", values, "familys");
            return (Criteria) this;
        }

        public Criteria andFamilysNotIn(List<Integer> values) {
            addCriterion("familys not in", values, "familys");
            return (Criteria) this;
        }

        public Criteria andFamilysBetween(Integer value1, Integer value2) {
            addCriterion("familys between", value1, value2, "familys");
            return (Criteria) this;
        }

        public Criteria andFamilysNotBetween(Integer value1, Integer value2) {
            addCriterion("familys not between", value1, value2, "familys");
            return (Criteria) this;
        }

        public Criteria andSbpIsNull() {
            addCriterion("sbp is null");
            return (Criteria) this;
        }

        public Criteria andSbpIsNotNull() {
            addCriterion("sbp is not null");
            return (Criteria) this;
        }

        public Criteria andSbpEqualTo(Integer value) {
            addCriterion("sbp =", value, "sbp");
            return (Criteria) this;
        }

        public Criteria andSbpNotEqualTo(Integer value) {
            addCriterion("sbp <>", value, "sbp");
            return (Criteria) this;
        }

        public Criteria andSbpGreaterThan(Integer value) {
            addCriterion("sbp >", value, "sbp");
            return (Criteria) this;
        }

        public Criteria andSbpGreaterThanOrEqualTo(Integer value) {
            addCriterion("sbp >=", value, "sbp");
            return (Criteria) this;
        }

        public Criteria andSbpLessThan(Integer value) {
            addCriterion("sbp <", value, "sbp");
            return (Criteria) this;
        }

        public Criteria andSbpLessThanOrEqualTo(Integer value) {
            addCriterion("sbp <=", value, "sbp");
            return (Criteria) this;
        }

        public Criteria andSbpIn(List<Integer> values) {
            addCriterion("sbp in", values, "sbp");
            return (Criteria) this;
        }

        public Criteria andSbpNotIn(List<Integer> values) {
            addCriterion("sbp not in", values, "sbp");
            return (Criteria) this;
        }

        public Criteria andSbpBetween(Integer value1, Integer value2) {
            addCriterion("sbp between", value1, value2, "sbp");
            return (Criteria) this;
        }

        public Criteria andSbpNotBetween(Integer value1, Integer value2) {
            addCriterion("sbp not between", value1, value2, "sbp");
            return (Criteria) this;
        }

        public Criteria andHyprxIsNull() {
            addCriterion("hyprx is null");
            return (Criteria) this;
        }

        public Criteria andHyprxIsNotNull() {
            addCriterion("hyprx is not null");
            return (Criteria) this;
        }

        public Criteria andHyprxEqualTo(Integer value) {
            addCriterion("hyprx =", value, "hyprx");
            return (Criteria) this;
        }

        public Criteria andHyprxNotEqualTo(Integer value) {
            addCriterion("hyprx <>", value, "hyprx");
            return (Criteria) this;
        }

        public Criteria andHyprxGreaterThan(Integer value) {
            addCriterion("hyprx >", value, "hyprx");
            return (Criteria) this;
        }

        public Criteria andHyprxGreaterThanOrEqualTo(Integer value) {
            addCriterion("hyprx >=", value, "hyprx");
            return (Criteria) this;
        }

        public Criteria andHyprxLessThan(Integer value) {
            addCriterion("hyprx <", value, "hyprx");
            return (Criteria) this;
        }

        public Criteria andHyprxLessThanOrEqualTo(Integer value) {
            addCriterion("hyprx <=", value, "hyprx");
            return (Criteria) this;
        }

        public Criteria andHyprxIn(List<Integer> values) {
            addCriterion("hyprx in", values, "hyprx");
            return (Criteria) this;
        }

        public Criteria andHyprxNotIn(List<Integer> values) {
            addCriterion("hyprx not in", values, "hyprx");
            return (Criteria) this;
        }

        public Criteria andHyprxBetween(Integer value1, Integer value2) {
            addCriterion("hyprx between", value1, value2, "hyprx");
            return (Criteria) this;
        }

        public Criteria andHyprxNotBetween(Integer value1, Integer value2) {
            addCriterion("hyprx not between", value1, value2, "hyprx");
            return (Criteria) this;
        }

        public Criteria andTcIsNull() {
            addCriterion("tc is null");
            return (Criteria) this;
        }

        public Criteria andTcIsNotNull() {
            addCriterion("tc is not null");
            return (Criteria) this;
        }

        public Criteria andTcEqualTo(Double value) {
            addCriterion("tc =", value, "tc");
            return (Criteria) this;
        }

        public Criteria andTcNotEqualTo(Double value) {
            addCriterion("tc <>", value, "tc");
            return (Criteria) this;
        }

        public Criteria andTcGreaterThan(Double value) {
            addCriterion("tc >", value, "tc");
            return (Criteria) this;
        }

        public Criteria andTcGreaterThanOrEqualTo(Double value) {
            addCriterion("tc >=", value, "tc");
            return (Criteria) this;
        }

        public Criteria andTcLessThan(Double value) {
            addCriterion("tc <", value, "tc");
            return (Criteria) this;
        }

        public Criteria andTcLessThanOrEqualTo(Double value) {
            addCriterion("tc <=", value, "tc");
            return (Criteria) this;
        }

        public Criteria andTcIn(List<Double> values) {
            addCriterion("tc in", values, "tc");
            return (Criteria) this;
        }

        public Criteria andTcNotIn(List<Double> values) {
            addCriterion("tc not in", values, "tc");
            return (Criteria) this;
        }

        public Criteria andTcBetween(Double value1, Double value2) {
            addCriterion("tc between", value1, value2, "tc");
            return (Criteria) this;
        }

        public Criteria andTcNotBetween(Double value1, Double value2) {
            addCriterion("tc not between", value1, value2, "tc");
            return (Criteria) this;
        }

        public Criteria andLdlIsNull() {
            addCriterion("ldl is null");
            return (Criteria) this;
        }

        public Criteria andLdlIsNotNull() {
            addCriterion("ldl is not null");
            return (Criteria) this;
        }

        public Criteria andLdlEqualTo(Double value) {
            addCriterion("ldl =", value, "ldl");
            return (Criteria) this;
        }

        public Criteria andLdlNotEqualTo(Double value) {
            addCriterion("ldl <>", value, "ldl");
            return (Criteria) this;
        }

        public Criteria andLdlGreaterThan(Double value) {
            addCriterion("ldl >", value, "ldl");
            return (Criteria) this;
        }

        public Criteria andLdlGreaterThanOrEqualTo(Double value) {
            addCriterion("ldl >=", value, "ldl");
            return (Criteria) this;
        }

        public Criteria andLdlLessThan(Double value) {
            addCriterion("ldl <", value, "ldl");
            return (Criteria) this;
        }

        public Criteria andLdlLessThanOrEqualTo(Double value) {
            addCriterion("ldl <=", value, "ldl");
            return (Criteria) this;
        }

        public Criteria andLdlIn(List<Double> values) {
            addCriterion("ldl in", values, "ldl");
            return (Criteria) this;
        }

        public Criteria andLdlNotIn(List<Double> values) {
            addCriterion("ldl not in", values, "ldl");
            return (Criteria) this;
        }

        public Criteria andLdlBetween(Double value1, Double value2) {
            addCriterion("ldl between", value1, value2, "ldl");
            return (Criteria) this;
        }

        public Criteria andLdlNotBetween(Double value1, Double value2) {
            addCriterion("ldl not between", value1, value2, "ldl");
            return (Criteria) this;
        }

        public Criteria andHDiabIsNull() {
            addCriterion("h_diab is null");
            return (Criteria) this;
        }

        public Criteria andHDiabIsNotNull() {
            addCriterion("h_diab is not null");
            return (Criteria) this;
        }

        public Criteria andHDiabEqualTo(Integer value) {
            addCriterion("h_diab =", value, "hDiab");
            return (Criteria) this;
        }

        public Criteria andHDiabNotEqualTo(Integer value) {
            addCriterion("h_diab <>", value, "hDiab");
            return (Criteria) this;
        }

        public Criteria andHDiabGreaterThan(Integer value) {
            addCriterion("h_diab >", value, "hDiab");
            return (Criteria) this;
        }

        public Criteria andHDiabGreaterThanOrEqualTo(Integer value) {
            addCriterion("h_diab >=", value, "hDiab");
            return (Criteria) this;
        }

        public Criteria andHDiabLessThan(Integer value) {
            addCriterion("h_diab <", value, "hDiab");
            return (Criteria) this;
        }

        public Criteria andHDiabLessThanOrEqualTo(Integer value) {
            addCriterion("h_diab <=", value, "hDiab");
            return (Criteria) this;
        }

        public Criteria andHDiabIn(List<Integer> values) {
            addCriterion("h_diab in", values, "hDiab");
            return (Criteria) this;
        }

        public Criteria andHDiabNotIn(List<Integer> values) {
            addCriterion("h_diab not in", values, "hDiab");
            return (Criteria) this;
        }

        public Criteria andHDiabBetween(Integer value1, Integer value2) {
            addCriterion("h_diab between", value1, value2, "hDiab");
            return (Criteria) this;
        }

        public Criteria andHDiabNotBetween(Integer value1, Integer value2) {
            addCriterion("h_diab not between", value1, value2, "hDiab");
            return (Criteria) this;
        }

        public Criteria andCvdIsNull() {
            addCriterion("cvd is null");
            return (Criteria) this;
        }

        public Criteria andCvdIsNotNull() {
            addCriterion("cvd is not null");
            return (Criteria) this;
        }

        public Criteria andCvdEqualTo(Integer value) {
            addCriterion("cvd =", value, "cvd");
            return (Criteria) this;
        }

        public Criteria andCvdNotEqualTo(Integer value) {
            addCriterion("cvd <>", value, "cvd");
            return (Criteria) this;
        }

        public Criteria andCvdGreaterThan(Integer value) {
            addCriterion("cvd >", value, "cvd");
            return (Criteria) this;
        }

        public Criteria andCvdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cvd >=", value, "cvd");
            return (Criteria) this;
        }

        public Criteria andCvdLessThan(Integer value) {
            addCriterion("cvd <", value, "cvd");
            return (Criteria) this;
        }

        public Criteria andCvdLessThanOrEqualTo(Integer value) {
            addCriterion("cvd <=", value, "cvd");
            return (Criteria) this;
        }

        public Criteria andCvdIn(List<Integer> values) {
            addCriterion("cvd in", values, "cvd");
            return (Criteria) this;
        }

        public Criteria andCvdNotIn(List<Integer> values) {
            addCriterion("cvd not in", values, "cvd");
            return (Criteria) this;
        }

        public Criteria andCvdBetween(Integer value1, Integer value2) {
            addCriterion("cvd between", value1, value2, "cvd");
            return (Criteria) this;
        }

        public Criteria andCvdNotBetween(Integer value1, Integer value2) {
            addCriterion("cvd not between", value1, value2, "cvd");
            return (Criteria) this;
        }

        public Criteria andLvhIsNull() {
            addCriterion("lvh is null");
            return (Criteria) this;
        }

        public Criteria andLvhIsNotNull() {
            addCriterion("lvh is not null");
            return (Criteria) this;
        }

        public Criteria andLvhEqualTo(Integer value) {
            addCriterion("lvh =", value, "lvh");
            return (Criteria) this;
        }

        public Criteria andLvhNotEqualTo(Integer value) {
            addCriterion("lvh <>", value, "lvh");
            return (Criteria) this;
        }

        public Criteria andLvhGreaterThan(Integer value) {
            addCriterion("lvh >", value, "lvh");
            return (Criteria) this;
        }

        public Criteria andLvhGreaterThanOrEqualTo(Integer value) {
            addCriterion("lvh >=", value, "lvh");
            return (Criteria) this;
        }

        public Criteria andLvhLessThan(Integer value) {
            addCriterion("lvh <", value, "lvh");
            return (Criteria) this;
        }

        public Criteria andLvhLessThanOrEqualTo(Integer value) {
            addCriterion("lvh <=", value, "lvh");
            return (Criteria) this;
        }

        public Criteria andLvhIn(List<Integer> values) {
            addCriterion("lvh in", values, "lvh");
            return (Criteria) this;
        }

        public Criteria andLvhNotIn(List<Integer> values) {
            addCriterion("lvh not in", values, "lvh");
            return (Criteria) this;
        }

        public Criteria andLvhBetween(Integer value1, Integer value2) {
            addCriterion("lvh between", value1, value2, "lvh");
            return (Criteria) this;
        }

        public Criteria andLvhNotBetween(Integer value1, Integer value2) {
            addCriterion("lvh not between", value1, value2, "lvh");
            return (Criteria) this;
        }

        public Criteria andAfIsNull() {
            addCriterion("af is null");
            return (Criteria) this;
        }

        public Criteria andAfIsNotNull() {
            addCriterion("af is not null");
            return (Criteria) this;
        }

        public Criteria andAfEqualTo(Integer value) {
            addCriterion("af =", value, "af");
            return (Criteria) this;
        }

        public Criteria andAfNotEqualTo(Integer value) {
            addCriterion("af <>", value, "af");
            return (Criteria) this;
        }

        public Criteria andAfGreaterThan(Integer value) {
            addCriterion("af >", value, "af");
            return (Criteria) this;
        }

        public Criteria andAfGreaterThanOrEqualTo(Integer value) {
            addCriterion("af >=", value, "af");
            return (Criteria) this;
        }

        public Criteria andAfLessThan(Integer value) {
            addCriterion("af <", value, "af");
            return (Criteria) this;
        }

        public Criteria andAfLessThanOrEqualTo(Integer value) {
            addCriterion("af <=", value, "af");
            return (Criteria) this;
        }

        public Criteria andAfIn(List<Integer> values) {
            addCriterion("af in", values, "af");
            return (Criteria) this;
        }

        public Criteria andAfNotIn(List<Integer> values) {
            addCriterion("af not in", values, "af");
            return (Criteria) this;
        }

        public Criteria andAfBetween(Integer value1, Integer value2) {
            addCriterion("af between", value1, value2, "af");
            return (Criteria) this;
        }

        public Criteria andAfNotBetween(Integer value1, Integer value2) {
            addCriterion("af not between", value1, value2, "af");
            return (Criteria) this;
        }

        public Criteria andCognitiveIsNull() {
            addCriterion("cognitive is null");
            return (Criteria) this;
        }

        public Criteria andCognitiveIsNotNull() {
            addCriterion("cognitive is not null");
            return (Criteria) this;
        }

        public Criteria andCognitiveEqualTo(Integer value) {
            addCriterion("cognitive =", value, "cognitive");
            return (Criteria) this;
        }

        public Criteria andCognitiveNotEqualTo(Integer value) {
            addCriterion("cognitive <>", value, "cognitive");
            return (Criteria) this;
        }

        public Criteria andCognitiveGreaterThan(Integer value) {
            addCriterion("cognitive >", value, "cognitive");
            return (Criteria) this;
        }

        public Criteria andCognitiveGreaterThanOrEqualTo(Integer value) {
            addCriterion("cognitive >=", value, "cognitive");
            return (Criteria) this;
        }

        public Criteria andCognitiveLessThan(Integer value) {
            addCriterion("cognitive <", value, "cognitive");
            return (Criteria) this;
        }

        public Criteria andCognitiveLessThanOrEqualTo(Integer value) {
            addCriterion("cognitive <=", value, "cognitive");
            return (Criteria) this;
        }

        public Criteria andCognitiveIn(List<Integer> values) {
            addCriterion("cognitive in", values, "cognitive");
            return (Criteria) this;
        }

        public Criteria andCognitiveNotIn(List<Integer> values) {
            addCriterion("cognitive not in", values, "cognitive");
            return (Criteria) this;
        }

        public Criteria andCognitiveBetween(Integer value1, Integer value2) {
            addCriterion("cognitive between", value1, value2, "cognitive");
            return (Criteria) this;
        }

        public Criteria andCognitiveNotBetween(Integer value1, Integer value2) {
            addCriterion("cognitive not between", value1, value2, "cognitive");
            return (Criteria) this;
        }

        public Criteria andPoorMemoryIsNull() {
            addCriterion("poor_memory is null");
            return (Criteria) this;
        }

        public Criteria andPoorMemoryIsNotNull() {
            addCriterion("poor_memory is not null");
            return (Criteria) this;
        }

        public Criteria andPoorMemoryEqualTo(Integer value) {
            addCriterion("poor_memory =", value, "poorMemory");
            return (Criteria) this;
        }

        public Criteria andPoorMemoryNotEqualTo(Integer value) {
            addCriterion("poor_memory <>", value, "poorMemory");
            return (Criteria) this;
        }

        public Criteria andPoorMemoryGreaterThan(Integer value) {
            addCriterion("poor_memory >", value, "poorMemory");
            return (Criteria) this;
        }

        public Criteria andPoorMemoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("poor_memory >=", value, "poorMemory");
            return (Criteria) this;
        }

        public Criteria andPoorMemoryLessThan(Integer value) {
            addCriterion("poor_memory <", value, "poorMemory");
            return (Criteria) this;
        }

        public Criteria andPoorMemoryLessThanOrEqualTo(Integer value) {
            addCriterion("poor_memory <=", value, "poorMemory");
            return (Criteria) this;
        }

        public Criteria andPoorMemoryIn(List<Integer> values) {
            addCriterion("poor_memory in", values, "poorMemory");
            return (Criteria) this;
        }

        public Criteria andPoorMemoryNotIn(List<Integer> values) {
            addCriterion("poor_memory not in", values, "poorMemory");
            return (Criteria) this;
        }

        public Criteria andPoorMemoryBetween(Integer value1, Integer value2) {
            addCriterion("poor_memory between", value1, value2, "poorMemory");
            return (Criteria) this;
        }

        public Criteria andPoorMemoryNotBetween(Integer value1, Integer value2) {
            addCriterion("poor_memory not between", value1, value2, "poorMemory");
            return (Criteria) this;
        }

        public Criteria andInjuryIsNull() {
            addCriterion("injury is null");
            return (Criteria) this;
        }

        public Criteria andInjuryIsNotNull() {
            addCriterion("injury is not null");
            return (Criteria) this;
        }

        public Criteria andInjuryEqualTo(Integer value) {
            addCriterion("injury =", value, "injury");
            return (Criteria) this;
        }

        public Criteria andInjuryNotEqualTo(Integer value) {
            addCriterion("injury <>", value, "injury");
            return (Criteria) this;
        }

        public Criteria andInjuryGreaterThan(Integer value) {
            addCriterion("injury >", value, "injury");
            return (Criteria) this;
        }

        public Criteria andInjuryGreaterThanOrEqualTo(Integer value) {
            addCriterion("injury >=", value, "injury");
            return (Criteria) this;
        }

        public Criteria andInjuryLessThan(Integer value) {
            addCriterion("injury <", value, "injury");
            return (Criteria) this;
        }

        public Criteria andInjuryLessThanOrEqualTo(Integer value) {
            addCriterion("injury <=", value, "injury");
            return (Criteria) this;
        }

        public Criteria andInjuryIn(List<Integer> values) {
            addCriterion("injury in", values, "injury");
            return (Criteria) this;
        }

        public Criteria andInjuryNotIn(List<Integer> values) {
            addCriterion("injury not in", values, "injury");
            return (Criteria) this;
        }

        public Criteria andInjuryBetween(Integer value1, Integer value2) {
            addCriterion("injury between", value1, value2, "injury");
            return (Criteria) this;
        }

        public Criteria andInjuryNotBetween(Integer value1, Integer value2) {
            addCriterion("injury not between", value1, value2, "injury");
            return (Criteria) this;
        }

        public Criteria andMiniStrokeIsNull() {
            addCriterion("mini_stroke is null");
            return (Criteria) this;
        }

        public Criteria andMiniStrokeIsNotNull() {
            addCriterion("mini_stroke is not null");
            return (Criteria) this;
        }

        public Criteria andMiniStrokeEqualTo(Integer value) {
            addCriterion("mini_stroke =", value, "miniStroke");
            return (Criteria) this;
        }

        public Criteria andMiniStrokeNotEqualTo(Integer value) {
            addCriterion("mini_stroke <>", value, "miniStroke");
            return (Criteria) this;
        }

        public Criteria andMiniStrokeGreaterThan(Integer value) {
            addCriterion("mini_stroke >", value, "miniStroke");
            return (Criteria) this;
        }

        public Criteria andMiniStrokeGreaterThanOrEqualTo(Integer value) {
            addCriterion("mini_stroke >=", value, "miniStroke");
            return (Criteria) this;
        }

        public Criteria andMiniStrokeLessThan(Integer value) {
            addCriterion("mini_stroke <", value, "miniStroke");
            return (Criteria) this;
        }

        public Criteria andMiniStrokeLessThanOrEqualTo(Integer value) {
            addCriterion("mini_stroke <=", value, "miniStroke");
            return (Criteria) this;
        }

        public Criteria andMiniStrokeIn(List<Integer> values) {
            addCriterion("mini_stroke in", values, "miniStroke");
            return (Criteria) this;
        }

        public Criteria andMiniStrokeNotIn(List<Integer> values) {
            addCriterion("mini_stroke not in", values, "miniStroke");
            return (Criteria) this;
        }

        public Criteria andMiniStrokeBetween(Integer value1, Integer value2) {
            addCriterion("mini_stroke between", value1, value2, "miniStroke");
            return (Criteria) this;
        }

        public Criteria andMiniStrokeNotBetween(Integer value1, Integer value2) {
            addCriterion("mini_stroke not between", value1, value2, "miniStroke");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：person_question
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 类注释
     * Criterion
     * 数据库表：person_question
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}